spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: servicecloud-config-dept
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location:  classpath:mybatis/mybatis-cfg.xml
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.atguigu.entities
eureka: 
  client: 
    service-url:
      defaultZone: #http://localhost:7001/eureka/
          http://eureka7001.com:7001/eureka/
info: 
 app-name : 尚学堂
 company.name:  beijingshangguigu
 
 
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: servicecloud-config-dept
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location:  classpath:mybatis/mybatis-cfg.xml
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.atguigu.entities
eureka: 
  client: 
    service-url:
      defaultZone: #http://localhost:7001/eureka/
          http://eureka7001.com:7001/eureka/
info: 
 app-name : 尚学堂
 company.name:  beijingshangguigu